version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
    - backend

  backend:
    depends_on:
      - mysqldb
    container_name: simple-url-backend
    build: ./simple-url-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - BASE_URL=$REACT_APP_API_URL
    stdin_open: true
    tty: true
    networks:
      - backend
      - frontend

  frontend:
    depends_on:
      - backend
    build:
      context: ./simple-url-front
      args:
        - REACT_APP_API_BASE_URL=$REACT_APP_API_URL

    container_name: simple-url-frontend
    ports:
       - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
  frontend: